# Generated by Django 2.2.2 on 2019-11-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CaseCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('case_name', models.CharField(max_length=30)),
                ('case_details', models.CharField(max_length=30)),
                ('doc', models.DateField()),
                ('evidence', models.CharField(max_length=30)),
                ('evidence_img', models.FileField(default=False, upload_to='evidence_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='CreateAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent_id', models.IntegerField()),
                ('Agent_Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Contact_Number', models.IntegerField()),
                ('Qualification', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Defence_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Postings',
            fields=[
                ('Job', models.CharField(default=False, max_length=30, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=30)),
                ('Qualification', models.CharField(max_length=50)),
                ('Percentage', models.IntegerField()),
                ('Experience', models.IntegerField(help_text='In Years')),
                ('Last_date', models.DateField()),
                ('Location', models.CharField(max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='success_stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=50)),
                ('Suggession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Dob', models.DateField()),
                ('Qualification', models.CharField(max_length=30)),
                ('percentage', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Contact_Number', models.IntegerField()),
                ('JOB_TITLE', models.ManyToManyField(to='app.Job_Postings')),
            ],
        ),
    ]
