# Generated by Django 2.2.2 on 2019-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecreation',
            name='case_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='createagent',
            name='Agent_id',
            field=models.IntegerField(unique=True),
        ),
    ]
