# Generated by Django 2.2.2 on 2019-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assign_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_agent',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
