# Generated by Django 2.2.2 on 2019-11-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191106_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAssign_Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('agent_id', models.ManyToManyField(to='app.CreateAgent')),
                ('case_id', models.ManyToManyField(to='app.CaseCreation')),
            ],
        ),
    ]
