# Generated by Django 2.2.2 on 2019-11-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_caseassign_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecreation',
            name='case_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='createagent',
            name='Agent_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
