# Generated by Django 2.2.2 on 2019-11-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191106_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='First_Name',
            new_name='Full_Name',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='Last_Name',
        ),
    ]
