# Generated by Django 2.2.2 on 2019-11-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191107_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='JOB_TITLE',
        ),
        migrations.AddField(
            model_name='applicants',
            name='JOB_TITLE',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
