# Generated by Django 2.2.2 on 2019-11-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191107_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecreation',
            name='Agent_id',
            field=models.IntegerField(default=False),
        ),
    ]
