# Generated by Django 2.2.2 on 2019-11-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_casecreation_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Min_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('upass', models.CharField(max_length=30)),
            ],
        ),
    ]
