# Generated by Django 2.2.2 on 2019-11-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_min_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('Agent_id', models.IntegerField()),
                ('cstatus', models.CharField(max_length=20)),
                ('other_evidence', models.FileField(upload_to='other_images/')),
            ],
        ),
    ]
